#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  scripts/package_esp_release_bundle.sh --input-dir /abs/path/dist/esp/vX.Y.Z --version vX.Y.Z --output-dir /abs/path

Default behavior:
  - Verify an ESP release bundle generated by ./esp-bin-build.sh
  - Emit a tar.gz archive that preserves the versioned directory layout
  - Copy per-board single-bin firmware plus release metadata into a flat release asset directory
EOF
}

require_file() {
  local path="$1"
  local label="$2"
  if [[ ! -f "$path" ]]; then
    echo "Error: missing ${label}: $path" >&2
    exit 1
  fi
}

input_dir=""
version=""
output_dir=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --input-dir)
      shift
      [[ $# -gt 0 ]] || { echo "Error: --input-dir requires a value." >&2; exit 1; }
      input_dir="$1"
      ;;
    --version)
      shift
      [[ $# -gt 0 ]] || { echo "Error: --version requires a value." >&2; exit 1; }
      version="$1"
      ;;
    --output-dir)
      shift
      [[ $# -gt 0 ]] || { echo "Error: --output-dir requires a value." >&2; exit 1; }
      output_dir="$1"
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Error: unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
  shift
done

[[ -n "$input_dir" && -n "$version" && -n "$output_dir" ]] || {
  usage >&2
  exit 1
}
[[ -d "$input_dir" ]] || {
  echo "Error: input dir not found: $input_dir" >&2
  exit 1
}

require_file "$input_dir/SHA256SUMS" "release checksums"
require_file "$input_dir/release-catalog.json" "release catalog"
require_file "$input_dir/release-report.json" "release report"

bundle_name="$(basename "$input_dir")"
mkdir -p "$output_dir"

tar -C "$(dirname "$input_dir")" -czf "$output_dir/beetle-${version}-esp-release-bundle.tar.gz" "$bundle_name"
cp "$input_dir/release-catalog.json" "$output_dir/beetle-${version}-esp-release-catalog.json"
cp "$input_dir/release-report.json" "$output_dir/beetle-${version}-esp-release-report.json"
cp "$input_dir/SHA256SUMS" "$output_dir/beetle-${version}-esp-SHA256SUMS.txt"

bin_found=0
while IFS= read -r bin_file; do
  [[ -n "$bin_file" ]] || continue
  bin_found=1
  board_name="$(basename "$bin_file" .bin)"
  require_file "$input_dir/${board_name}.manifest.json" "board manifest for $board_name"
  cp "$bin_file" "$output_dir/beetle-${version}-${board_name}.bin"
  cp "$input_dir/${board_name}.manifest.json" "$output_dir/beetle-${version}-${board_name}.manifest.json"
done < <(find "$input_dir" -maxdepth 1 -type f -name '*.bin' | LC_ALL=C sort)

if [[ "$bin_found" -eq 0 ]]; then
  echo "Error: no board firmware bins found under $input_dir" >&2
  exit 1
fi
